CREATE SCHEMA IF NOT EXISTS PHOTOS;

CREATE TABLE IF NOT EXISTS PHOTOS.Photo (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    file_name VARCHAR(255),
    content_type VARCHAR(255),
    data BLOB
)